import { Geist, Geist_Mono } from "next/font/google";
import Navbar from './navbar/page'; 
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar /> {/* Hiển thị Navbar ở đây */}
        {children} {/* Nội dung các trang sẽ được render tại đây */}
      </body>
    </html>
  );
}
